version: '3.1'
services:
  mqtt:
      build: .
      image: hot/mosqui
      container_name: mqtt
      restart: always
      ports:
        - "1883:1883"
        - "8080:8080"
      volumes:
        - ./data/mqtt/config:/mqtt/config
        - ./data/mqtt/data:/mqtt/data
        - ./data/mqtt/log:/mqtt/log
      depends_on:
        - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"