version: '3'
services:
  mqtt:
      image: hot/mosqui
      container_name: mqtt
      restart: always
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./data/mqtt/config:/mqtt/config
        - ./data/mqtt/data:/mqtt/data
        - ./data/mqtt/log:/mqtt/log